<a href="https://colab.research.google.com/github/rkbo07/cast/blob/main/practice4_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arrayA = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arrayB = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print("arrayA is ")
print(arrayA)
print("")
print("arrayB is ")
print(np.array(arrayB))

print("")
arrayAp = np.reshape(arrayA, (3, 3))
print("arrayAp is ")
print(arrayAp)
print("")
print("multiplication array is ")
print(np.dot(arrayAp, arrayB))

arrayA is 
[1, 2, 3, 4, 5, 6, 7, 8, 9]

arrayB is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arrayAp is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

multiplication array is 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
